[workspace]
authors = ["atleer <atle.rimehaug@gmail.com>"]
channels = ["conda-forge"]
name = "Intro-to-Deep-Learning-with-PyTorch"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --name wshop_dl_pytorch"

[dependencies]
python = "3.12.*"
pytorch = ">=2.7.1,<3"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"
seaborn = ">=0.13.2,<0.14"
pip = ">=25.3,<26"
pingouin = ">=0.5.5,<0.6"
scipy = ">=1.17.0,<2"
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
torchvision = ">=0.22.0,<0.23"
scikit-learn = ">=1.7.1,<2"
ipywidgets = ">=8.1.7,<9"
pyocclient = ">=0.6,<0.7"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
torchviz = ">=0.0.3"
torchinfo = ">=1.8.0, <2"